### ISSUE TITLE
Correcciones TP2 2024 2C

### ISSUE THREAD

**Issue by thiagopservian** [lmaydana/TDA-Buchwald#3]
**2. Algoritmo**
**2.1 Codigo**
Podrían modularizar para no tener tantos `if  (if  else )else` anidados.
Cuando explican y definen su ecuación de recurrencia no consideran el caso de tener 1 sola moneda ni el de 0 monedas. En su implementación sí esta considerado, ya que se entra al `else 0` para el caso de una sola moneda, y el for nunca itera nada si es 0 monedas, y devuelve 0 porque se inicializo la martiz en 0, pero no por que calcule o considere.  
Si bien el la condición de los indices la mencionan en la explicacion, o sea lo que se suma si se cumple una condicion en especifico, no se explica que hacer en otros casos. Y tampoco esta definido en la ecuación.
_"Este valor se calcula como: opcion izquierda = monedas[ini]+ganancia segun mateo.
Donde ganancia segun mateo es: matriz[ini + 2][f in] (si ini + 2 <= f in)"_ ... o 0 en otros casos.
Sería agregar la consideración del else que tienen en el codigo.

ECUACIÓN
![image](https://github.com/user-attachments/assets/747fa32e-26be-421b-963f-e34e5ee82fbd)

Toda el pensamiento logico para plantearlo es correcto, es decir que la ecuación se fija el maximo entre agarrar la izquierda o derecha y dentro de cada opción debe considerarse que moneda eligio mateo. Pero no para tomar en cuenta la moneda que eligio mateo no tenemos que agarrar el minimo entre dos sub-optimos. Ya que de esta manera no es optima, y lo podemos ver con el siguiente contra-ejemplo. Para una unas monedas: [1, 10, 5, 235, 200 ]
![image](https://github.com/user-attachments/assets/6bb82583-610d-49b8-b733-ce0209e17155)
Su ecuación de recurrencia calcula todo bien menos el último paso, es decir la posición [0] [4] de la matriz, donde devuelve 206 con el siguiente procedimiento:
![image](https://github.com/user-attachments/assets/0cc22048-6d7b-48bf-8c3e-ad32c1b27a6f)
Pero la solución optima para [1, 10, 5, 235, 200] en realidad es:
S = [1, 235, 5] = 241
M = [200, 10, -] = 210

Otra cosa, si bien nunca ponemos los casos bases en la definicion de la ecuación de recurrencia, en este caso si podemos llegar a hacerlo, ya que la ecuación que ustedes proponen da lugar a las siguientes situaciones:
si tenemos 1 moneda donde ini = fin = 0, estaremos accediendo en los `min` a:
-`opt[2][0]`
-`opt[1][-1]`
-`opt[0][-2]`
Todas posiciones invalidas porque estan fuera del alcance del opt. Esto se puede solucionar de dos maneras, tal y como ustedes consideraron en el codigo implementado y en la explicacion con la condición de que siempre que queramos acceder a cualquier instancia de un `opt[a] [b] ` debe cumplirse que a <= b, sino 0 para otros casos. Sería explicitar esta condicion en la ecuacion de recurrencia para los subcasos como les explique mas arriba.
La otra opción es explicitar los casos bases en la ecuación, de tal manera que nos queda:
opt[ini][fin] = 

- `0 si ini > fin`
- ` monedas[ini] si ini = fin`
- `ecuacion de concurrencia, para otros casos`

Ahora, el codigo implementado esta bien y funciona correctamente de manera optima ya que ustedes no implementaron la ecuación definida en el informe, sino que implementaron otra que si es correcta. Que funciona y plantea lo mismo explicado en la introducción pero la unica diferencia es que en vez de calcular el minimo entre dos sub-problemas, se fijan que moneda agarraria mateo en cada caso y sumamos el óptimo para los sub-indices tras la eleccion de mateo.
Por ejemplo si queremos calcular la opcion_a donde Sophia agarra la primera moneda sería:
`monedas[ini] + min(matriz[ini + 2][fin], matriz[ini + 1][fin - 1])` NO
`monedas[ini] + matriz[new_ini][new_fin]` SI
donde new_ini y new_fin serían los indices tras la elección de mateo. Ustedes en su implementación hacen exactamente esto, se fijan que moneda elegiria mateo y buscan el optimo para los indices sacando la moneda de sophia y la moneda de la eleccion de mateo para eso caso. 
Sería pasar lo que pusieron en la implementacion a la ecuación de recurrencia.

**2.2. Optimalidad**
Demostración por Induccion:
Es semi-identica a la que hicieron en greedy de inducción que estaba mal, pero lo que hicieron acá fue plantear un hiptesis inductiva para un k <= n-1 lo que da la posibilidad de no ser un valor fijo, sino muchos a la vez y por ende si podemos decir que para k-1 hay solución y ademas se tiene en consideración el caso de la elección de mateo, y que tomaremos el maximo para los dos caminos posibles. Lo único que esta mal es esto:
![image](https://github.com/user-attachments/assets/de9c2b37-aa02-482e-9dcd-29e2b03f8fcf)
que no pasa por la demostración, sino porque la ecuación esta mal como les dije antes. Si pusieran la ecuación correctamente, esto punto ya estaría impecable.
Lo comento porque quizas les choca que esta demostración este bien, pero la de greedy mal al ser tan similares. 

Ejemplo de Ejecución:
La explicación de como se llena la matriz esta muy bien, casualmente agarraron un ejemplo con la que los minimos funciona y queda identica a que si usaran la ecuación correcta. Lo que sí van a tener que cambiar el paso a paso porque el minimo ya no va a estar más.  
La explicacón de como realizar la reconstruccion se salta demasiados pasos. 
_"Luego de comparar, vamos a ver que habiamos elegido la moneda ini (numero 5)."_ 
¿Que comparaciones? ¿Como fue el procedimiento paso a paso para determinar que efectivamente esa moneda fue elegida?

El resto de cosas estan bien, los test, la complejidad y los análisis de los gráficos tambien.

Hace un rato les habia mandado otras correcciones, les pido mil disculpas si es que las llegaron a leer y se confundieron. Lo voy a tener en cuenta para este tp como para el siguiente.
Les voy a pedir que redefinan la ecuación de recurrencia, y si pueden el seguimiento para la reconstrucción. 
Como tarde una semana en corregir, sepan que si llegan a estar justos con las fechas limite o algo me avisan y lo podemos mover tranquilamente.
El tp esta muy bien en general, con la ecuación corregida puedo cerrar con un 8. Saludos

**Comment by CastellanoBenja** [comment]
Hola Thiego, ahi ya subimos los cambios

**Comment by thiagopservian** [comment]
Perfecto, cierro con 8 el tp.
